// DO NOT EDIT. generated by github.com/tinywasm/orm

package client

import (
	"github.com/tinywasm/model"
	"github.com/tinywasm/form/input"
)

func (m *SetModeArgs) ModelName() string {
	return "set_mode_args"
}

var _schemaSetModeArgs = []model.Field{
		{Name: "mode", Type: model.FieldText, NotNull: true, Widget: input.Text()},
	}

func (m *SetModeArgs) Schema() []model.Field { return _schemaSetModeArgs }

func (m *SetModeArgs) Pointers() []any { return []any{&m.Mode} }

func (m *SetModeArgs) IsNil() bool { return m == nil }

func (m *SetModeArgs) EncodeFields(w model.FieldWriter) {
	w.String("mode", m.Mode)
}

func (m *SetModeArgs) DecodeFields(r model.FieldReader) {
	if v, ok := r.String("mode"); ok { m.Mode = v }
}

type SetModeArgsList []*SetModeArgs

func (s *SetModeArgsList) Schema() []model.Field { return nil }
func (s *SetModeArgsList) Pointers() []any     { return nil }
func (s *SetModeArgsList) Len() int             { return len(*s) }
func (s *SetModeArgsList) At(i int) model.Fielder { return (*s)[i] }
func (s *SetModeArgsList) Append() model.Fielder  { v := &SetModeArgs{}; *s = append(*s, v); return v }
func (s *SetModeArgsList) IsNil() bool          { return s == nil }
func (s *SetModeArgsList) EncodeFields(_ model.FieldWriter) {}
func (s *SetModeArgsList) DecodeFields(_ model.FieldReader) {}

func (m *SetModeArgs) Validate(action byte) error {
	return model.ValidateFields(action, m)
}

