package client

// SetModeArgs defines arguments for the wasm_set_mode tool.
// ormc:formonly
type SetModeArgs struct {
	Mode string `input:"required,enum=L;M;S"`
}

// Schema will be generated by ormc.
func (a *SetModeArgs) Schema() string { return "" }
