// DO NOT EDIT. generated by github.com/tinywasm/orm

package client

import (
	"github.com/tinywasm/fmt"
)

func (m *SetModeArgs) ModelName() string {
	return "set_mode_args"
}

var _schemaSetModeArgs = []fmt.Field{
		{Name: "mode", Type: fmt.FieldText, NotNull: true},
	}

func (m *SetModeArgs) Schema() []fmt.Field { return _schemaSetModeArgs }

func (m *SetModeArgs) Pointers() []any { return []any{&m.Mode} }

func (m *SetModeArgs) IsNil() bool { return m == nil }

func (m *SetModeArgs) EncodeFields(w fmt.FieldWriter) {
	w.String("mode", m.Mode)
}

func (m *SetModeArgs) DecodeFields(r fmt.FieldReader) error {
	if v, ok := r.String("mode"); ok { m.Mode = v }
	return nil
}

type SetModeArgsList []*SetModeArgs

func (s *SetModeArgsList) Schema() []fmt.Field { return nil }
func (s *SetModeArgsList) Pointers() []any     { return nil }
func (s *SetModeArgsList) Len() int             { return len(*s) }
func (s *SetModeArgsList) At(i int) fmt.Fielder { return (*s)[i] }
func (s *SetModeArgsList) Append() fmt.Fielder  { v := &SetModeArgs{}; *s = append(*s, v); return v }
func (s *SetModeArgsList) IsNil() bool          { return s == nil }
func (s *SetModeArgsList) EncodeFields(_ fmt.FieldWriter) {}
func (s *SetModeArgsList) DecodeFields(_ fmt.FieldReader) error { return nil }

func (m *SetModeArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

