// DO NOT EDIT. generated by github.com/tinywasm/orm

package client

import (
	"github.com/tinywasm/fmt"
	"github.com/tinywasm/form/input"
)

var _schemaSetModeArgs = []fmt.Field{
		{Name: "mode", Type: fmt.FieldText, NotNull: true, Widget: input.Text()},
	}

func (m *SetModeArgs) Schema() []fmt.Field { return _schemaSetModeArgs }

func (m *SetModeArgs) Pointers() []any {
	return []any{
		&m.Mode,
	}
}

func (m *SetModeArgs) Validate(action byte) error {
	return fmt.ValidateFields(action, m)
}

